[build]
builder = "nixpacks"

[build.nixpacksConfig]
javaVersion = "21"

[deploy]
startCommand = "java -jar target/Project-Acougue-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[environments.production.variables]
JAVA_VERSION = "21"