[build]
builder = "nixpacks"

[build.nixpacksConfig]
javaVersion = "17"

[deploy]
startCommand = "java -jar target/Project-Acougue-0.0.1-SNAPSHOT.jar"
restartPolicyType = "on_failure"

[environments.production.variables]
JAVA_VERSION = "17"